# Generated by Django 5.1.7 on 2025-03-16 03:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0003_cliente_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cotizacion',
            old_name='fecha',
            new_name='fecha_emision',
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='condiciones_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='condiciones_pago',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='fecha_vencimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='itemcotizacion',
            name='unidad_medida',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
