# Generated by Django 5.1.7 on 2025-03-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizaciones', '0004_rename_fecha_cotizacion_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='porcentaje_descuentos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='porcentaje_impuestos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
